apiVersion: v1
kind: Namespace
metadata:
  name: meetingbot-local
  labels:
    name: meetingbot-local
    environment: local
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meetingbot-service-account
  namespace: meetingbot-local
  labels:
    app: meetingbot
    environment: local
