apiVersion: v1
kind: Namespace
metadata:
  name: meetingbot
  labels:
    name: meetingbot
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meetingbot-service-account
  namespace: meetingbot
  labels:
    app: meetingbot

