apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: meetingbot
  name: meetingbot-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: meetingbot-rolebinding
  namespace: meetingbot
subjects:
- kind: ServiceAccount
  name: meetingbot-service-account
  namespace: meetingbot
roleRef:
  kind: Role
  name: meetingbot-role
  apiGroup: rbac.authorization.k8s.io

