apiVersion: v1
kind: Service
metadata:
  name: meetingbot-server
  namespace: meetingbot
spec:
  selector:
    app: meetingbot-server
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP

